### ISSUE TITLE
Withdraw your party

### ISSUE THREAD

**Issue by dawidpjoubert** [openpolitics/manifesto#570]
The current manifesto is a joke, has conflicting ideas, includes substantial core economical changes which on their own would be difficult to implement, lacks understanding of how business operates and how taxation works .

You guys have a nice idea but to be anything more than a joke, circle-jerk, waste of time you need to reject ridiculous ideas & flash out how you are going to achieve certain proposals.

**Comment by Floppy** [comment]
Thanks! Please help us make it better :)

**Comment by dawidpjoubert** [comment]
I wish to. However I fail to see the purpose of any of this while we have first past the post system rather than proportional.

Regards,
Dawid

**Comment by Floppy** [comment]
That does make it hard, certainly; FPTP is a massive problem for democracy in the UK. But, we hope to either build something viable in the long term, or show that being open about politics is possible and get the existing parties to operate better. Either way, we've got to try :)

**Comment by dawidpjoubert** [comment]
Good luck and Godspeed with your challenge.

**Comment by Xyleneb** [comment]
>The current manifesto is a joke, has conflicting ideas, includes substantial core economical changes which on their own would be difficult to implement, lacks understanding of how business operates and how taxation works.

@dawidpjoubert I know this topic was closed 6 months ago but I'm curious as to which particular areas you were looking at?

>I wish to help make it better but I can't because I don't see the point...

It's mental exercise for me, and that's desirable because I need problem solving, critical thinking, focus and things to better handle real life stuff. Alternatively if I spend too long here, the same real life stuff catches up to me rather overwhelmingly and then fatigue begins setting in... but yeah it's a worthwhile thing to do if it'll sharpen the mind a little. I'm talking about the policy end though ~ the campaign stuff isn't really my cup of tea.
